main/app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', TemplateView.as_view(template_name='main/about.html'), name='about'),
    path('goal/add/', views.add_goal, name='goal_add'),
    path('income/add/', views.add_income, name='income_add'),
    path('expense/add/', views.add_expense, name='expense_add'),
    path('goal/edit/<int:goal_id>/', views.edit_goal, name='goal_edit'),
    path('income/edit/<int:transaction_id>/',
          views.edit_income,
          name='income_edit'),
    path('expense/edit/<int:transaction_id>/',
          views.edit_expense,
          name='expense_edit'),
    path('goal/delete/<int:goal_id>/', views.delete_goal, name='goal_delete'),
    path('income/delete/<int:transaction_id>/',
          views.delete_income,
          name='income_delete'),
    path('expense/delete/<int:transaction_id>/',
          views.delete_expense,
          name='expense_delete'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from app import views
from allauth.account.views import PasswordChangeView
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = [
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/first_page_login/', views.login_with_email, name='first_page_login'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='account_login'),
    path('accounts/password/reset/', views.CustomPasswordResetView.as_view(), name='account_reset_password1'),
    path('accounts/password/change/done/', TemplateView.as_view(template_name='account/password_change_done.html'), name='account_password_change_done'),
    path('accounts/password/change/', PasswordChangeView.as_view(success_url='done/'), name='password_change'),
    path('accounts/register/', views.RegistrationView.as_view(), name='register'),
    path('accounts/password_reset/notification/', views.password_reset_notification, name='password_reset_notification'),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/user/financial-info/', views.UserFinancialInfoView.as_view(), name='user-financial-info'),
    path('', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

main/templates/main/transaction/add_expense.html
{% extends 'base.html' %}

{% block title %}Добавление расходов{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Добавление расходов</h1>
        <form action="{% url 'app:expense_add' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Добавить расход</button>
        </form>
    </div>
{% endblock %}

main/templates/main/transaction/add_income.html
{% extends 'base.html' %}

{% block title %}Добавление расходов{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Добавление доходов</h1>
    <form action="{% url 'app:income_add' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <input type="submit" class="btn btn-primary" value="добавить расход">
    </form>
</div>
{% endblock %}

main/templates/main/transaction/confirm_delete_expense.html
{% extends 'base.html' %}

{% block title %}Удаление расхода{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Удаление расхода</h1>
        <p class="alert alert-danger">Вы уверены, что хотите удалить этот расход?</p>
        <div class="text-center">
            <form action="{% url 'app:expense_delete' entity.id %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form>
            <form action="{% url 'app:index' %}" method="get" class="d-inline">
                <button type="submit" class="btn btn-secondary">Отмена</button>
            </form>
        </div>
    </div>
{% endblock %}

main/templates/main/transaction/confirm_delete_income.html
{% extends 'base.html' %}

{% block title %}Удаление дохода{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Удаление дохода</h1>
        <p class="alert alert-danger">Вы уверены, что хотите удалить этот доход?</p>
        <div class="text-center">
            <form action="{% url 'app:income_delete' entity.id %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form>
            <form action="{% url 'app:index' %}" method="get" class="d-inline">
                <button type="submit" class="btn btn-secondary">Отмена</button>
            </form>
        </div>
    </div>
{% endblock %}

main/templates/main/transaction/edit_expense.html
{% extends 'base.html' %}

{% block title %}Редактирование расхода{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Редактирование расхода</h1>
        <form action="{% url 'app:expense_edit' entity.id %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Изменить</button>
        </form>
        <form action="{% url 'app:index' %}" method="get" class="mt-3">
            <button type="submit" class="btn btn-secondary">Отмена</button>
        </form>
    </div>
{% endblock %}

main/templates/main/transaction/edit_income.html
{% extends 'base.html' %}

{% block title %}Редактирование дохода{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Редактирование дохода</h1>
        <form action="{% url 'app:income_edit' entity.id %}" method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Изменить</button>
        </form>
        <form action="{% url 'app:index' %}" method="get" class="mt-3">
            <button type="submit" class="btn btn-secondary">Отмена</button>
        </form>
    </div>
{% endblock %}