main/app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', TemplateView.as_view(template_name='main/about.html'), name='about'),
    path('goal/add/', views.add_goal, name='goal_add'),
    path('income/add/', views.add_income, name='income_add'),
    path('expense/add/', views.add_expense, name='expense_add'),
    path('goal/edit/<int:goal_id>/', views.edit_goal, name='goal_edit'),
    path('income/edit/<int:transaction_id>/',
          views.edit_income,
          name='income_edit'),
    path('expense/edit/<int:transaction_id>/',
          views.edit_expense,
          name='expense_edit'),
    path('goal/delete/<int:goal_id>/', views.delete_goal, name='goal_delete'),
    path('income/delete/<int:transaction_id>/',
          views.delete_income,
          name='income_delete'),
    path('expense/delete/<int:transaction_id>/',
          views.delete_expense,
          name='expense_delete'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from app import views
from allauth.account.views import PasswordChangeView
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = [
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/first_page_login/', views.login_with_email, name='first_page_login'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='account_login'),
    path('accounts/password/reset/', views.CustomPasswordResetView.as_view(), name='account_reset_password1'),
    path('accounts/password/change/done/', TemplateView.as_view(template_name='account/password_change_done.html'), name='account_password_change_done'),
    path('accounts/password/change/', PasswordChangeView.as_view(success_url='done/'), name='password_change'),
    path('accounts/register/', views.RegistrationView.as_view(), name='register'),
    path('accounts/password_reset/notification/', views.password_reset_notification, name='password_reset_notification'),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/user/financial-info/', views.UserFinancialInfoView.as_view(), name='user-financial-info'),
    path('', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>{% block title %}Финансовый помощник{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand font-monospace" href="/">Финансовый помощник</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link disabled">{{ request.user.username }} </span>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'account_logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-link nav-link" value="Выход">
                        </form>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'account_change_password' %}" method="get" class="d-inline">
                            <input type="submit" class="btn btn-link nav-link" value="Сменить пароль">
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Войти</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:about' %}">О нас</a>
                </li>
            </ul>
        </div>
    </nav>

    <div id="content" class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="text-center mt-4" style="background-color: #f8f9fa; padding: 20px; border-top: 2px solid #e0e0e0;">
        <hr style="border: 0; border-top: 1px solid #ccc; margin: 10px 0;">
        <small style="color: #555; font-size: 14px;">Все права защищены &copy; 2024 FinanceHelper</small>
    </footer>

</html>