main/app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', TemplateView.as_view(template_name='main/about.html'), name='about'),
    path('goal/add/', views.add_goal, name='goal_add'),
    path('income/add/', views.add_income, name='income_add'),
    path('expense/add/', views.add_expense, name='expense_add'),
    path('goal/edit/<int:goal_id>/', views.edit_goal, name='goal_edit'),
    path('income/edit/<int:transaction_id>/',
          views.edit_income,
          name='income_edit'),
    path('expense/edit/<int:transaction_id>/',
          views.edit_expense,
          name='expense_edit'),
    path('goal/delete/<int:goal_id>/', views.delete_goal, name='goal_delete'),
    path('income/delete/<int:transaction_id>/',
          views.delete_income,
          name='income_delete'),
    path('expense/delete/<int:transaction_id>/',
          views.delete_expense,
          name='expense_delete'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from app import views
from allauth.account.views import PasswordChangeView
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = [
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/first_page_login/', views.login_with_email, name='first_page_login'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='account_login'),
    path('accounts/password/reset/', views.CustomPasswordResetView.as_view(), name='account_reset_password1'),
    path('accounts/password/change/done/', TemplateView.as_view(template_name='account/password_change_done.html'), name='account_password_change_done'),
    path('accounts/password/change/', PasswordChangeView.as_view(success_url='done/'), name='password_change'),
    path('accounts/register/', views.RegistrationView.as_view(), name='register'),
    path('accounts/password_reset/notification/', views.password_reset_notification, name='password_reset_notification'),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/user/financial-info/', views.UserFinancialInfoView.as_view(), name='user-financial-info'),
    path('', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

main/templates/main/goal/add.html
{% extends 'base.html' %}

{% block title %}Добавление новой цели{% endblock %}

{% block content %}
  <div class="container my-5">
    <h1 class="mb-4">Новая цель накопления:</h1>
    <form action="{% url 'app:goal_add' %}" method="post" class="form-group">
      {% csrf_token %}
      <div class="mb-3">
      {{ form.as_p }}
        </div>
      <button type="submit" class="btn btn-primary">добавить цель</button>
    </form>
  </div>
{% endblock %}

main/templates/main/goal/confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удаление цели{% endblock %}

{% block content %}
  <div class="container my-5">
    <h1 class="mb-4">Удаление цели</h1>
    <form action="{% url 'app:goal_delete' goal.id %}" method="post" class="form-group">
      {% csrf_token %}
        <button type="submit" class="btn btn-danger">удалить</button>
        <a href="{% url 'app:index' %}" class="btn btn-secondary">отмена</a>
    </form>
  </div>
{% endblock %}

main/templates/main/goal/edit.html
{% extends 'base.html' %}

{% block title %}Редактирование цели{% endblock %}

{% block content %}
  <div class="container my-5">
    <h1 class="mb-4">Редактирование цели:</h1>
    <form action="{% url 'app:goal_edit' goal.id %}" method="post" class="form-group">
      {% csrf_token %}
      {{ form.as_p }}
        <button type="submit" class="btn btn-primary">изменить</button>
        <a href="{% url 'app:index' %}" class="btn btn-secondary">отмена</a>
    </form>
  </div>
{% endblock %}